create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  note_key text not null,
  author text not null check (char_length(author) between 1 and 80),
  content text not null check (char_length(content) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists notes_note_key_created_at_idx
  on public.notes (note_key, created_at desc);

alter table public.notes enable row level security;

create policy "Public read notes"
on public.notes
for select
to anon
using (true);

create policy "Public insert notes"
on public.notes
for insert
to anon
with check (true);
